# Generated by Django 5.1.7 on 2025-04-03 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_estimate_estimateitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='color',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='model',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='year',
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='estimate',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='billing.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
